repositories:
  #  - name: bitnami
  #  url: https://charts.bitnami.com/bitnami
releases:
  - name: "myapp"
    chart: "deploy/"
    namespace: myapp
    createNamespace: true
    values:
      - values-shared.yaml
      - values-{{ .Environment.Name }}.yaml
    secrets:
      - secrets-{{ .Environment.Name }}.yaml
environments:
  prod:
    kubeContext: [YOUR KUBE CONTEXT HERE ]
  dev:
    kubeContext: [YOUR KUBE CONTEXT HERE ]
